spring:
  application:
    name: AuthenticationApp
  datasource:
    url: jdbc:mysql://localhost:3306/ekart
    username: root
    password: ducat
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
    